### ISSUE TITLE
Tons of lag when going through chunk boundaries

### ISSUE THREAD

**Issue by QPCrummer** [Spottedleaf/Starlight#10]
Phosphor has recently just fixed this Minecraft Bug. Is it possible for you to as well?

**Comment by Spottedleaf** [comment]
As far as I'm aware starlight eradicates lighting-related spikes when crossing chunk boundaries due to how the skylight nibbles are being managed. In fact, no light work is done at all for loading in chunks right now - so you shouldn't be seeing spikes related to lighting.

Coming in 0.0.2 (soon) is a new skylight management system that's similar to vanilla, and it wont suffer from chunk boundary issues.

**Comment by QPCrummer** [comment]
cool
