### ISSUE TITLE
Does the Chunk Border Lag bug exist if the client doesn't Starlight

### ISSUE THREAD

**Issue by QPCrummer** [Spottedleaf/Starlight#11]
I had chunk lag because I didn't have the mod on client, just on server. That seemed to be fixed when I installed it on my client. I don't know if this is a bug or not.

**Comment by Spottedleaf** [comment]
yes, the client needs the mod (the server side isn't required, but since the skylight management is a bit broken right now having server side eliminates a lot of the existing light problems right now)

if you have further questions you can contact me on discord via the link found in the README here: https://github.com/Spottedleaf/Tuinity
