### ISSUE TITLE
Further Optimize + Continue Develop

### ISSUE THREAD

**Issue by ItsukaHiro** [Spottedleaf/Starlight#185]
It's just my experinence so I'm not sure: When I use Starlight in 1.20.1, although it's true that FPS gap between have and no-have Starlight is really close (seem cannot notice if FPS under 100), the total performance is better when I have Starlight. It's about:
- Chunk-Gen: idk but is faster, actually, and can be see ingame.
- Input-lag: My laptop have an issue about input-lag when game just launched. Though Starlight can not fix it (obviously :V) but it's seem reduce it, somehow.
- FPS Stability: Actually if I saw the frametime graph, Starlight take less time than vanilla.

So I think instead of just porting it to new version, can you optimize it further? It's just my though and my suggestion.

**Comment by frqnny** [comment]
Are you sure it's not placebo effect? I'm sure the dev knows what he is talking about when he says that Starlight isn't needed.

**Comment by ItsukaHiro** [comment]
> Are you sure it's not placebo effect? I'm sure the dev knows what he is talking about when he says that Starlight isn't needed.

Sure man. At first I play 1.20.1 without Starlight, it's good, but sometimes isn't. And then with Starlight, everything seem better.

**Comment by Spottedleaf** [comment]
It's hard for me to measure the chunk system (TACS) performance of Starlight vs Vanilla due to some technical details about how both light engines manage state (although it is true that Starlight manages state in a far more performant manner) - for example, it actually does matter how many chunks are loaded and I've not really figured out at what chunk count threshold it matters. However, the Vanilla light engine state management may be prone to cause GC issues, but again it depends on the number of chunks. The GC issues may also affect users differently; I would expect lower core systems to be more affected than ones with higher cores for example. There really are too many variables to nail this issue down to anything other than "it depends" unfortunately. 

The TACS difference may also result in different chunk generation speeds due to the issues described above, but it's not very easy to measure that difference if it exists at all.

Other than the TACS difference, I don't see Starlight really doing much to matter.
