### ISSUE TITLE
Server hang with starlight and chisels and bits installed

### ISSUE THREAD

**Issue by TCwater** [Spottedleaf/Starlight#26]
https://paste.ubuntu.com/p/sBQBWX4JdN/

**Comment by Spottedleaf** [comment]
That mod is reading tile entity state in a manner different to vanilla. Server side code for vanilla guarantees that the light engine wont actually try to read tile entity data. But this mod decides to bypass it for some reason - and so, it tries to read the tile entity data off of the main thread. However the chunk isn't ready because it's in lighting - so it waits until the chunk is generated. Except of course, if the light thread is waiting for it to complete then it's waiting on itself. So it'll never complete, hence the stall.
There's nothing I can do, as this will happen even in vanilla. You should take that report (and what I said here) to the mod author.

**Comment by WenXin20** [comment]
Hello, it looks like it was reported to them, but it was closed as invalid.
ChiselsAndBits/Chisels-and-Bits#600

**Comment by Spottedleaf** [comment]
Well that's a shame.
