### ISSUE TITLE
Incompatibility with Bobby

### ISSUE THREAD

**Issue by GiantLuigi4** [Spottedleaf/Starlight#38]
![image](https://user-images.githubusercontent.com/49770992/112076599-12442600-8b51-11eb-8c38-0b5ffc83efff.png)
![image](https://user-images.githubusercontent.com/49770992/112076663-3b64b680-8b51-11eb-8679-b341ee6c04d0.png)
This is only really noticeable if bobby is installed, however it does happen
Nothing major, just minorly annoying

**Comment by Spottedleaf** [comment]
what exactly am I looking at

**Comment by GiantLuigi4** [comment]
Skylight being ignored in chunks being rendered because of [bobby](https://www.curseforge.com/minecraft/mc-mods/bobby)

**Comment by Boobies** [comment]
This ticked should probably be closed. It makes sense for things to be this way, as Starlight uses a different format for skylight data.

**Comment by Boobies** [comment]
Perhaps of relevance: https://github.com/Johni0702/bobby/issues/18#issuecomment-805834654

**Comment by Spottedleaf** [comment]
This looks to me like the lighting data isn't being loaded correctly. Not really surprising to me given I don't respect the vanilla light hook, and of course the mod has written its own implementation for parsing chunks from NBT (although vanilla is doing things in its standard load method that make using it not viable on the client, or even the server in some cases).

**Comment by Spottedleaf** [comment]
Next version will try to remedy the technical differences. I'll probably have to move lighting data to be stored in the light engine just like how vanilla does it, rather on the individual chunks themselves.

**Comment by Spottedleaf** [comment]
> 
> 
> Next version will try to remedy the technical differences. I'll probably have to move lighting data to be stored in the light engine just like how vanilla does it, rather on the individual chunks themselves.

Nah wont happen, I just remembered there were good reasons I moved light data to chunks, mostly around defending against race conditions in chunk loading/unloading.

**Comment by byalvaroft** [comment]
So is there any chance that both mods will be compatible ever?
The fps boost that I get from Starlight is really impressive and highly needed with high render distances with Bobby.

**Comment by SecretlyJealous** [comment]
> So is there any chance that both mods will be compatible ever?
> The fps boost that I get from Starlight is really impressive and highly needed with high render distances with Bobby.

I agree, bobby is a must have if you are playing on servers that have a low render distance (which is a lot of servers)

**Comment by Johni0702** [comment]
> So is there any chance that both mods will be compatible ever?

Yes, but it's not particularly high priority for me (especially not while starlight is still in beta) because

> The fps boost that I get from Starlight is really impressive and highly needed with high render distances with Bobby.

No, it's not needed for Bobby at all.
And the reason it's not is directly connected to this issue: The vanilla lighting engine (don't actually know about starlight's performance in that area) is somehow **really** slow when it comes to loading/unloading lots of chunks on the client (up to multiple seconds of freezing after teleports), and light in fake chunks never changes anyway, so, Bobby as of version 1.1.0 (which is why starlight was compatible with earlier versions) completely bypasses the lighting engine for all fake chunks. So whether you use vanilla or starlight will make absolutely no difference for the fake chunks (assuming this bug was fixed).

Now, starlight will still ofc have an effect on the real chunks sent by the server (and on the server-side for singleplayer), so compatibility is still desirable but, as mentioned in the comment linked above, I tried and couldn't get it to work within reasonable time, so it is what it is until starlight leaves beta and I try again.

**Comment by Spottedleaf** [comment]
I've moved the save logic to its own class that should be runnable from the clientside:
https://github.com/Tuinity/Starlight/blob/fabric/src/main/java/ca/spottedleaf/starlight/common/util/SaveUtil.java

**Comment by ReflectorXD** [comment]
My pull request #45 attempts to fix this issue

**Comment by Amaroq-Clearwater** [comment]
Now I can't help but also think of the LoD mod, FarPlane2. I wonder if Starlight and/or Bobby will also have problems with that.

**Comment by mikenrafter** [comment]
Any progress on this front?

**Comment by ramblade** [comment]
Bump bc I would like this feature to be fixed

**Comment by Chew** [comment]
Starlight is an open-source project.

**Comment by Sushant-Padha** [comment]
> Now I can't help but also think of the LoD mod, FarPlane2. I wonder if Starlight and/or Bobby will also have problems with that.

Isn't that a Forge mod for 1.12 only? Or is there a fabric port?

**Comment by Slackadays** [comment]
Any progress with this issue?

**Comment by Corvus20** [comment]
Update: Issue persists with latest 1.18 versions of both mods

**Comment by Dreig-Michihi** [comment]
Yes, bobby issue is very sad, I'm not sure what is better to choose for me: starlight or bobby :с

**Comment by Anoaxx** [comment]
Starlight obviously?

**Comment by pparanoiidd** [comment]
Farsight is a bobby replacement and works just fine with Starlight

**Comment by ramblade** [comment]
This incompatibility was fixed in bobby version 3.0.1 for 1.18.1 so this issue can be closed now.

**Comment by Woctor-Dho** [comment]
Thank you!
